site_name: BitMakeLab
site_url: https://thinkcreatelearn.co.uk/bitmake
theme:
  name: material
  features:
    - navigation.tabs  # Enables the tabbed navigation style for the site
  palette:
    primary: custom # Sets the primary color of the site to a custom color defined in the extra.css file
    accent: custom # Sets the accent color of the site to a custom color defined in the extra.css file
  logo: assets/logo.png
  font:
    text: Work Sans

# Site navigation structure
nav:
  - Home: index.md
  - Projects: 
    - Overview: projects/overview.md
    - Wheeled Robots:
      - Overview: projects/wheeled-robots/overview.md
      - Build a Basic Robot: projects/wheeled-robots/project1.01/index.md
      - Add Lights to your Robot: projects/wheeled-robots/project1.02/index.md
      - Add Crash Sensors to your Robot: projects/wheeled-robots/project1.03/index.md
      - Build a Remote Control Robot: projects/wheeled-robots/project1.04/index.md
      - Add a Speed Control to your Remote: projects/wheeled-robots/project1.05/index.md
      - Build a Line Following Robot: projects/wheeled-robots/project1.06/index.md
      - Build an Obstacle Avoiding Robot: projects/wheeled-robots/project1.07/index.md  
    - Trains:
      - Overview: projects/trains/overview.md
      - Build a Train: projects/trains/project2.01/index.md
      - Add Lights to your Train: projects/trains/project2.02/index.md
      - Add Crash Sensors to your Train: projects/trains/project2.03/index.md
      - Add an Ultrasonic Sensor to your Train: projects/trains/project2.04/index.md
      - Build a Signalling System for Trains: projects/trains/project2.05/index.md
  - Reference: 
    - Overview: reference/overview.md
    - Inputs:
      - Overview: reference/inputs/overview/index.md
      - Button: reference/inputs/button/index.md
      - Potentiometer: reference/inputs/potentiometer/index.md
      - Keyboard: reference/inputs/keyboard/index.md
      - Ultrasonic Sensor: reference/inputs/ultrasonic-sensor/index.md
      - Line Follow Sensor: reference/inputs/line-follow-sensor/index.md
      - Light Sensor: reference/inputs/light-sensor/index.md
      - Joystick: reference/inputs/adafruit-joystick/index.md
      - Force Sensor: reference/inputs/force-sensor/index.md
      - Break Beam Sensor: reference/inputs/break-beam-sensor/index.md
    - Outputs:
      - Overview: reference/outputs/overview/index.md
      - LED: reference/outputs/led/index.md
      - Alphanumeric LED: reference/outputs/alphanumeric-led/index.md
    - Motors:
      - Overview: reference/motors/overview/index.md
      - DC Motor: reference/motors/dc-motor/index.md
      - Servo Motor: reference/motors/servo-motor/index.md
    - Working with Data:
      - Serial output: reference/working-with-data/serial-output/index.md
      - Data logging: reference/working-with-data/data-logging/index.md
  - Make the kit:
      - Overview: make-the-kit/overview.md
  - Blog:
    - blog/index.md
  - About: about.md  

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - attr_list # add attributes to some markdown elements such as images using curly braces
  - md_in_html # allows markdown to be used inside HTML blocks

  # Python markdown extensions for extra functionality
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  # Social links
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
  social:
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/tcreatelearn/

    - icon: fontawesome/brands/github
      link: https://github.com/lewfer

  generator: false # Hides the "Generated by MkDocs" message in the footer of the site

  # Custom variables for use in the macros plugin
  bmlgithubpages: https://lewfer.github.io/BitMakeLab
  bmlgithub: https://github.com/lewfer/BitMakeLab/tree/main/

plugins:
  - blog # enables the blog functionality for the site https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
  - search # enables the search box in the top right of the site
  - macros # gives us the ability to use variables and macrosin our markdown files https://mkdocs-macros-plugin.readthedocs.io

exclude_docs: |
  - ^*

copyright: Copyright &copy; 2026 - Think Create Learn Ltd. Licensed under the Creative Commons BY-SA-NC-SA licence.